In [1]:
#create a numpy array containing 1 to 20 numbers using inbuilt function
import numpy as np
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [2]:
#create an array of all zeros with 10 elements and convert it to matrix
import numpy as np
arr=np.zeros(10)
print(arr)
arr=arr.reshape(2,5)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [3]:
#array containing even numbers from 2 to 20
import numpy as np
even=np.arange(2,21,2)
print(even)


[ 2  4  6  8 10 12 14 16 18 20]


In [4]:
#finding dimensions,shape,size,datatype and multiply every element by 2
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("Array:")
print(arr)
print("Dimensions:",arr.ndim)
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Datatype:",arr.dtype)
print("Multiply by 2:")
print(arr*2)


Array:
[[1 2 3]
 [4 5 6]]
Dimensions: 2
Shape: (2, 3)
Size: 6
Datatype: int64
Multiply by 2:
[[ 2  4  6]
 [ 8 10 12]]


In [5]:
#find sum,mean,max,min
import numpy as np
arr=np.array([10,20,30,40,50])
print("Array:",arr)
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Max:",np.max(arr))
print("Min:",np.min(arr))

Array: [10 20 30 40 50]
Sum: 150
Mean: 30.0
Max: 50
Min: 10
